config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :restaurants do
    resources :dishes
  end

  root 'welcome#index'

end

app/models/dish.rb
class Dish < ActiveRecord::Base
	belongs_to :restaurant

	has_attached_file :image, styles: { :medium => "300x300>" } #paperclip gem stuff
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/ #paperclip gem stuff

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	belongs_to :user
	has_many :dishes	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :restaurants


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


 private
  # Overwriting the sign_out redirect path method
  # def after_sign_out_path_for(resource_or_scope)
  #   root_path
  # end

  def after_sign_in_path_for(resource)
    restaurants_path
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
	before_action :set_restaurant
	before_action :set_dish, except: [:create]
	before_action :find_dish, only: [:show, :edit, :update, :destroy]

	def index
		@dishes = @restaurant.dishes.all(dish_params)
		# @pins = Pin.all.order("created_at DESC")
	end

	def create
		@dish = @restaurant.dishes.create(dish_params)
		redirect_to @restaurant 
	end

	def new
		@dish = @restaurant.dishes.create(dish_params)
	end

	def show
		dish = @restaurant.dishes.list
	end

	def edit
	end
	
	def update
		if @dish.update(dish_params)
			redirect_to @dish, notice: "Dish was Successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
		if @dish.destroy
			flash[:success] = "Dish was deleted"
		else
			flash[:error] = "Dish could not be deleted dude."	
		end
		redirect_to @restaurant	
	end
 	
	def complete
		@dish.update_attribute(:completed_at, Time.now)
		redirect_to @restaurant, notice: "Dish completed dude"
	end


	private
	def find_dish
		@dish = Dish.find(params[:id])
	end

	def set_restaurant 
		@restaurant = Restaurant.find(params[:restaurant_id])
	end

	def set_dish
		@dish = @restaurant.dishes.find(params[:id]) rescue Dish.new(name:"", description:"", yumyuck:"")		
	end

	def dish_params
		return nil if params[:dish].to_s == ''
		params[:dish].permit(:name, :description, :yumyuck, :image)
	end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [ ] 
    before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

	def index
		@restaurants = Restaurant.all.order("created_at DESC")
	end

	def show
	end

	def new
		@restaurant = current_user.restaurants.build
	end

	def create
		@restaurant = current_user.restaurants.build(restaurant_params)
		if @restaurant.save
			redirect_to @restaurant, notice: "Successfully created new Restaurant"
		else
			render 'new'
		end
	end

	def edit
	end
	
	def update
		if @restaurant.update(restaurant_params)
			redirect_to @restaurant, notice: "Restaurant was Successfully updated"
		else
			render 'edit'
		end
	end

	def destroy
	  @restaurant.destroy
	  redirect_to restaurants_path
	end



	private
	def set_restaurant
        @restaurant = Restaurant.find(params[:id])
    end

	def restaurant_params
		params.require(:restaurant).permit(:name, :description, :address)
	end

	def find_restaurant
		@restaurant = Restaurant.find(params[:id])
	end

	def get_dishes
		# Figure out how to get the dishes
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  	redirect_to "/yummy_yucky_2.html"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/welcome2_helper.rb
module Welcome2Helper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dishes/_dish.html.erb
  <div class="transitions-enabled" id="dishs">
    <div class="col-md-3" "col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading dish_image">
          <%= image_tag dish.image.url(:medium) %>
        </div>
        <div class="panel-body">
          <h2 id="dish-name-panel">
            <%= dish.name %>
          </h2>
          <p class="description">
            <%= dish.description %>
          </p>
          <p class="yumyuck">
            <%= dish.yumyuck %>
          </p> 
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-md-6">
              <p class="user"></p>

            </div>
            <div class="col-md-6">
              <div class="btn-group pull-right"> 
                <% if user_signed_in? %>
                  <%= link_to "Edit",  class: "btn btn-default" %>
                  <%= link_to "Delete", restaurant_dishes_path(@restaurant.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<% if false %> <!--BEGIN ERB COMMENT OUT-->
  <div class="transitions-enabled" id="dishs">
    <% @restaurant.dishes.each do |dish| %>
      <div class="box panel panel-default">
        <%= image_tag dish.image.url(:medium)%>
        <div class="panel-body">
          <h2>
            <%= dish.name %>
          </h2>
          <p class="description">
            <%= dish.description %>
          </p>
          <p class="yumyuck">
            <%= dish.yumyuck %>
          </p> 
        </div>
      </div>
    <% end %>
  </div>
<% end %> <!--END ERB COMMENT OUT-->

app/views/dishes/_form.html.erb
<%= simple_form_for([@restaurant, @restaurant.dishes.build]) do |f| %>
  <% if @restaurant.errors.any?  %>
    <div id="errors"></div>
    <h2></h2>
    <%= pluralize(@restaurant.errors.count, "error") %>
    prevented this Restaurant from saving
    <ul></ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  <% end %>

  <div class="form-group">
      <%= f.input :image, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :name, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control'} %>
  </div>
  <div class="form-group">
    <%= f.input :yumyuck, input_html: { class: 'form-control'} %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/dishes/edit.html.erb
<h1>Edit Dish</h1>
<%= render 'form' %>
<%= link_to "Cancel",  %>

app/views/dishes/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Dish for <%= @restaurant.name.upcase %></h1>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
        <p></p>
        <%= link_to "Back", :back %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DishRater</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
	<div class="">
	  <% if user_signed_in? %>
	    <div class="navbar-brand">
	      <%= link_to "Yummy Yucky", "/yummy_yucky.html" %>
	    </div>
	    <ul class="nav navbar-nav navbar-right">
	   	  <li>
			 <%= link_to "Restaurants", restaurants_path %> 
		  </li>
	      <li>
	        <%= link_to "New Restaurant", new_restaurant_path %>
	      </li>
	      <li>
	        <%= link_to "Account", edit_user_registration_path %>
	      </li>
	      <li>
	        <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
	      </li>
	    </ul>
	  <% else %>
	    <div class="navbar-brand">
	      <%= link_to "Yummy Yucky", "/yummy_yucky_2.html" %>
	    </div>
	    <ul class="nav navbar-nav navbar-right">
	      <li>
	        <%= link_to "Sign Up", new_user_registration_path %>
	      </li>
	      <li>
	        <%= link_to "Sign In", new_user_session_path %>
	      </li>
	    </ul>
	  <% end %>
	</div>
	</nav>
		
	<% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-info"  %> <!-- this is bootstrap -->
    <% end %>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<div class="panel-body">
  <%= simple_form_for @restaurant, html: {multipart: true} do |f| %>
    <% if @restaurant.errors.any?  %>
      <div id="errors"></div>
      <h2></h2>
      <%= pluralize(@restaurant.errors.count, "error") %>
      prevented this Restaurant from saving
      <ul></ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    <% end %>
    
    <div class="form-group">
      <%= f.input :name, input_html: { class: 'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.input :description, input_html: { class: 'form-control'} %>
    </div>
    <div class="form-group">
  	<%= f.input :address, input_html: { class: 'form-control'} %>
    </div>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h1>Edit <%= @restaurant.name.upcase %></h1>
			</div>
				<%= render 'form' %>
				<%= link_to "Delete #{@restaurant.name.upcase}",  restaurant_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
				<br>
				<br>
				<%= link_to "Cancel", restaurant_path %>
				<p></p>
		</div>
	</div>
</div>

app/views/restaurants/index.html.erb
<div class="restaurant_title_bar">
  <h3 id="my_restaurant">My Restaurants</h3>
</div>

<div class="container">
	<% @restaurants.each do |restaurant| %>
	  <div class="index_row clearfix">
	    <h2 class="restaurant_title"><%= link_to restaurant.name, restaurant %></h2>
	    <p id="restaurant_description"><%= restaurant.description %></p>
		  <div class="restaurant_menu">
		    <%= link_to "Dishes", restaurant %>  &nbsp;   | &nbsp;  
		    <%= link_to "New Dish", new_restaurant_dish_path(restaurant) %>  &nbsp;   | &nbsp; 
		    <%= link_to "Edit Restaurant", edit_restaurant_path(restaurant)%>  
		  </div >
	    <p id="menu_spacing"></p>
	    <p id="restaurant_address"><%= restaurant.address %></p>
	  </div>
	<% end %>
</div>

app/views/restaurants/new.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="row">
    	<div class="panel panel-default">
      		<div class="panel-heading">
				<h1>New Restaurant</h1>
			</div>
				<%= render 'form' %>
				<%= link_to " Back to Restaurants", restaurants_path %>
		</div>
	</div>
</div>

app/views/restaurants/show.html.erb
	<div class="restaurant_title_bar">
  	<!-- <h3 id="my_restaurant">My Restaurants</h3> -->
	<h2 id="my_restaurant"><%= @restaurant.name %></h2>
	<h4><%= link_to "Enter New Dish", new_restaurant_dish_path(@restaurant.id)%></h4>
	<br>
	<p id="restaurant_page_back_button"><%= link_to "Back", restaurants_path%></p>
</div>

<!-- <div>
	<%= link_to "Back", restaurants_path %>
	<%= link_to "Edit", edit_restaurant_path %>
	<%= link_to "Delete", restaurant_path, method: :delete, data: {confirm: "Are you sure?"} %>
</div> -->

<br></br>

<div >
	
	<%= render @restaurant.dishes %>  <!-- This grabs it from the _dish.html.erb -->
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>